//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 10:44:30 AM EST 
//

package gov.nih.tbi.commons.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for investigator_struct complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="investigator_struct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="middle_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="degrees" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="affiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "investigator_struct", propOrder = { "firstName", "middleName", "lastName", "degrees", "role",
        "affiliation" })
public class InvestigatorStruct
{

    @XmlElement(name = "first_name")
    protected String firstName;
    @XmlElement(name = "middle_name")
    protected String middleName;
    @XmlElement(name = "last_name", required = true)
    protected String lastName;
    protected String degrees;
    protected String role;
    protected String affiliation;

    public String getFullTitle()
    {

        String title = "";
        if (firstName != null)
        {
            title += firstName;
        }
        if (middleName != null)
        {
            title += " " + middleName;
        }
        if (lastName != null)
        {
            title += " " + lastName;
        }
        if (degrees != null)
        {
            title += ", " + degrees;
        }
        if (affiliation != null)
        {
            title += " (" + affiliation + ")";
        }
        return title;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirstName()
    {

        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFirstName(String value)
    {

        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMiddleName()
    {

        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMiddleName(String value)
    {

        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastName()
    {

        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastName(String value)
    {

        this.lastName = value;
    }

    /**
     * Gets the value of the degrees property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDegrees()
    {

        return degrees;
    }

    /**
     * Sets the value of the degrees property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDegrees(String value)
    {

        this.degrees = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRole()
    {

        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRole(String value)
    {

        this.role = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAffiliation()
    {

        return affiliation;
    }

    /**
     * Sets the value of the affiliation property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAffiliation(String value)
    {

        this.affiliation = value;
    }

}
