//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 10:44:30 AM EST 
//

package gov.nih.tbi.commons.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * generated
     * 
     */
    public ObjectFactory()
    {

    }
    /**
     * Create an instance of {@link YearMonthStruct }
     * 
     */
    public YearMonthStruct createYearMonthStruct() {
        return new YearMonthStruct();
    }

    /**
     * Create an instance of {@link ClinicalStudy }
     * 
     */
    public ClinicalStudy createClinicalStudy()
    {

        return new ClinicalStudy();
    }

    /**
     * Create an instance of {@link InvestigatorStruct }
     * 
     */
    public InvestigatorStruct createInvestigatorStruct()
    {

        return new InvestigatorStruct();
    }

    /**
     * Create an instance of {@link TextblockStruct }
     * 
     */
    public TextblockStruct createTextblockStruct()
    {

        return new TextblockStruct();
    }

    /**
     * Create an instance of {@link RequiredHeaderStruct }
     * 
     */
    public RequiredHeaderStruct createRequiredHeaderStruct()
    {

        return new RequiredHeaderStruct();
    }

    /**
     * Create an instance of {@link IdInfoStruct }
     * 
     */
    public IdInfoStruct createIdInfoStruct()
    {

        return new IdInfoStruct();
    }
}
