//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 10:44:30 AM EST 
//

package gov.nih.tbi.commons.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for textblock_struct complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="textblock_struct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="textblock" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "textblock_struct", propOrder = { "textblock" })
public class TextblockStruct
{

    @XmlElement(required = true)
    protected String textblock;

    /**
     * Gets the value of the textblock property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTextblock()
    {

        return textblock;
    }

    /**
     * Sets the value of the textblock property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTextblock(String value)
    {

        this.textblock = value;
    }

}
