/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package gov.nih.tbi.api.query.controller;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import gov.nih.tbi.api.query.model.StudyForm;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-01-13T11:29:56.281-05:00[America/New_York]")
@Api(value = "form", description = "the form API")
public interface FormApi {

    @ApiOperation(value = "Find form structures by study prefixed ID", nickname = "getFormByStudyPrefixedId", notes = "This service return form structures that are associated with the given study prefixed ID(s).", response = StudyForm.class, responseContainer = "List", authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "Form Structure", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = StudyForm.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "JWT is missing or invalid"),
        @ApiResponse(code = 404, message = "The specified resource was not found") })
    @RequestMapping(value = "/form/study",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<List<StudyForm>> getFormByStudyPrefixedId(@NotNull @Size(min=1) @ApiParam(value = "Study prefixed ID(s) to return associated form structures for.", required = true) @Valid @RequestParam(value = "prefixedId", required = true) List<String> prefixedId);

}
