//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 10:44:30 AM EST 
//

package gov.nih.tbi.repository.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * generated
     * 
     */
    public ObjectFactory()
    {

    }

    /**
     * Create an instance of {@link SubmissionPackage }
     * 
     */
    public SubmissionPackage createSubmissionPackage()
    {

        return new SubmissionPackage();
    }

    /**
     * Create an instance of {@link SubmissionDataFile }
     * 
     */
    public SubmissionDataFile createSubmissionDataFile()
    {

        return new SubmissionDataFile();
    }

    /**
     * Create an instance of {@link SubmissionTicket }
     * 
     */
    public SubmissionTicket createSubmissionTicket()
    {

        return new SubmissionTicket();
    }

    public DataFile createDataFile()
    {

        return new DataFile();
    }

    public DataStructureData createDataStructureData()
    {

        return new DataStructureData();
    }

    public DataElementData createDataElementData()
    {

        return new DataElementData();
    }

    public Record createRecord()
    {

        return new Record();
    }

    public RepeatableGroupRow createRepeatableGroupRow()
    {

        return new RepeatableGroupRow();
    }
}
