package gov.nih.tbi.service;

import java.io.UnsupportedEncodingException;
import java.util.Map;
import java.util.Set;

import gov.nih.tbi.service.model.DataCart;

public interface BioSampleManager {

	/**
	 * Returns a list of Coriell IDs from the current user's biosample queue
	 * 
	 * @return
	 */
	public Set<String> getBiosamplesFromQueue() throws UnsupportedEncodingException;

	/**
	 * Adds a selected biosample to the user's biosample queue
	 * 
	 * @param formName     form name for the sample
	 * @param biosampleRow biosample row URI map generated by
	 *                     InstancedDataManager.getNonRepeatingRowDataByUri
	 */
	public void addBiosampleToQueue(String formName, Map<String, String> biosampleRow)
			throws UnsupportedEncodingException;

	public Map<String, String> getNonRepeatingRowDataByUri(String formName, String rowUri, DataCart dataCart);
}
