//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.31 at 05:32:23 AM EDT 
//


package gov.nih.tbi.ordermanager.iu;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderMetadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Originator"/>
 *                   &lt;element ref="{}OriginatorOrderId"/>
 *                   &lt;element ref="{}OriginatorEmail" maxOccurs="unbounded"/>
 *                   &lt;element ref="{}OriginatorNote" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}Date"/>
 *         &lt;element ref="{}User"/>
 *         &lt;element ref="{}Institution"/>
 *         &lt;element ref="{}Grant"/>
 *         &lt;element ref="{}PowerAnalysis"/>
 *         &lt;element ref="{}SampleRequests"/>
 *         &lt;element ref="{}ShippingAddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderMetadata",
    "date",
    "user",
    "institution",
    "grant",
    "powerAnalysis",
    "sampleRequests",
    "shippingAddress"
})
@XmlRootElement(name = "Order")
public class Order {

    @XmlElement(name = "OrderMetadata", required = true)
    protected Order.OrderMetadata orderMetadata;
    @XmlElement(name = "Date", required = true)
    protected String date;
    @XmlElement(name = "User", required = true)
    protected User user;
    @XmlElement(name = "Institution", required = true)
    protected Institution institution;
    @XmlElement(name = "Grant", required = true)
    protected Grant grant;
    @XmlElement(name = "PowerAnalysis", required = true)
    protected String powerAnalysis;
    @XmlElement(name = "SampleRequests", required = true)
    protected SampleRequests sampleRequests;
    @XmlElement(name = "ShippingAddress", required = true)
    protected ShippingAddress shippingAddress;

    /**
     * Gets the value of the orderMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link Order.OrderMetadata }
     *     
     */
    public Order.OrderMetadata getOrderMetadata() {
        return orderMetadata;
    }

    /**
     * Sets the value of the orderMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order.OrderMetadata }
     *     
     */
    public void setOrderMetadata(Order.OrderMetadata value) {
        this.orderMetadata = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the institution property.
     * 
     * @return
     *     possible object is
     *     {@link Institution }
     *     
     */
    public Institution getInstitution() {
        return institution;
    }

    /**
     * Sets the value of the institution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Institution }
     *     
     */
    public void setInstitution(Institution value) {
        this.institution = value;
    }

    /**
     * Gets the value of the grant property.
     * 
     * @return
     *     possible object is
     *     {@link Grant }
     *     
     */
    public Grant getGrant() {
        return grant;
    }

    /**
     * Sets the value of the grant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grant }
     *     
     */
    public void setGrant(Grant value) {
        this.grant = value;
    }

    /**
     * Gets the value of the powerAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerAnalysis() {
        return powerAnalysis;
    }

    /**
     * Sets the value of the powerAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerAnalysis(String value) {
        this.powerAnalysis = value;
    }

    /**
     * Gets the value of the sampleRequests property.
     * 
     * @return
     *     possible object is
     *     {@link SampleRequests }
     *     
     */
    public SampleRequests getSampleRequests() {
        return sampleRequests;
    }

    /**
     * Sets the value of the sampleRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleRequests }
     *     
     */
    public void setSampleRequests(SampleRequests value) {
        this.sampleRequests = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingAddress }
     *     
     */
    public ShippingAddress getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingAddress }
     *     
     */
    public void setShippingAddress(ShippingAddress value) {
        this.shippingAddress = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Originator"/>
     *         &lt;element ref="{}OriginatorOrderId"/>
     *         &lt;element ref="{}OriginatorEmail" maxOccurs="unbounded"/>
     *         &lt;element ref="{}OriginatorNote" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originator",
        "originatorOrderId",
        "originatorEmail",
        "originatorNote"
    })
    public static class OrderMetadata {

        @XmlElement(name = "Originator", required = true)
        protected String originator;
        @XmlElement(name = "OriginatorOrderId", required = true)
        protected String originatorOrderId;
        @XmlElement(name = "OriginatorEmail", required = true)
        protected List<String> originatorEmail;
        @XmlElement(name = "OriginatorNote", required = true)
        protected List<String> originatorNote;

        /**
         * Gets the value of the originator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginator() {
            return originator;
        }

        /**
         * Sets the value of the originator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginator(String value) {
            this.originator = value;
        }

        /**
         * Gets the value of the originatorOrderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginatorOrderId() {
            return originatorOrderId;
        }

        /**
         * Sets the value of the originatorOrderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginatorOrderId(String value) {
            this.originatorOrderId = value;
        }

        /**
         * Gets the value of the originatorEmail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the originatorEmail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOriginatorEmail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOriginatorEmail() {
            if (originatorEmail == null) {
                originatorEmail = new ArrayList<String>();
            }
            return this.originatorEmail;
        }

        /**
         * Gets the value of the originatorNote property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the originatorNote property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOriginatorNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOriginatorNote() {
            if (originatorNote == null) {
                originatorNote = new ArrayList<String>();
            }
            return this.originatorNote;
        }

    }

}
