//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.31 at 05:32:23 AM EDT 
//


package gov.nih.tbi.ordermanager.iu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ShipToName"/>
 *         &lt;element ref="{}ShipToOrganization"/>
 *         &lt;element ref="{}ShipToAddress"/>
 *         &lt;element ref="{}ShipToAddress2"/>
 *         &lt;element ref="{}ShipToCity"/>
 *         &lt;element ref="{}ShipToState"/>
 *         &lt;element ref="{}ShipToZip"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shipToName",
    "shipToOrganization",
    "shipToPhone",
    "shipToAddress",
    "shipToAddress2",
    "shipToCity",
    "shipToState",
    "shipToZip",
    "shipToAffiliation",
    "shipToAffiliationPhone",
    "shipToAffiliationEmail",
    "shipToAffiliationSpecialInstructions"
})
@XmlRootElement(name = "ShippingAddress")
public class ShippingAddress {

    @XmlElement(name = "ShipToName", required = true)
    protected String shipToName;
    @XmlElement(name = "ShipToOrganization", required = true)
    protected String shipToOrganization;
    @XmlElement(name = "ShipToPhone", required = true)
    protected String shipToPhone;
    @XmlElement(name = "ShipToAddress", required = true)
    protected String shipToAddress;
    @XmlElement(name = "ShipToAddress2", required = true)
    protected String shipToAddress2;
    @XmlElement(name = "ShipToCity", required = true)
    protected String shipToCity;
    @XmlElement(name = "ShipToState", required = true)
    protected String shipToState;
    @XmlElement(name = "ShipToZip", required = true)
    protected String shipToZip;
    @XmlElement(name = "ShipToAffiliation", required = true)
    protected String shipToAffiliation;
    @XmlElement(name = "ShipToAffiliationPhone", required = true)
    protected String shipToAffiliationPhone;
    @XmlElement(name = "ShipToAffiliationEmail", required = true)
    protected String shipToAffiliationEmail;
    @XmlElement(name = "ShipToAffiliationSpecialInstructions", required = true)
    protected String shipToAffiliationSpecialInstructions;

    /**
     * Gets the value of the shipToName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToName() {
        return shipToName;
    }

    /**
     * Sets the value of the shipToName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToName(String value) {
        this.shipToName = value;
    }

    /**
     * Gets the value of the shipToOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToOrganization() {
        return shipToOrganization;
    }

    /**
     * Sets the value of the shipToOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToOrganization(String value) {
        this.shipToOrganization = value;
    }

    /**
     * Gets the value of the shipToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToAddress() {
        return shipToAddress;
    }

    /**
     * Sets the value of the shipToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToAddress(String value) {
        this.shipToAddress = value;
    }

    /**
     * Gets the value of the shipToAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToAddress2() {
        return shipToAddress2;
    }

    /**
     * Sets the value of the shipToAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToAddress2(String value) {
        this.shipToAddress2 = value;
    }

    /**
     * Gets the value of the shipToCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToCity() {
        return shipToCity;
    }

    /**
     * Sets the value of the shipToCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToCity(String value) {
        this.shipToCity = value;
    }

    /**
     * Gets the value of the shipToState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToState() {
        return shipToState;
    }

    /**
     * Sets the value of the shipToState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToState(String value) {
        this.shipToState = value;
    }

    /**
     * Gets the value of the shipToZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToZip() {
        return shipToZip;
    }

    /**
     * Sets the value of the shipToZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToZip(String value) {
        this.shipToZip = value;
    }

	public String getShipToPhone() {
		return shipToPhone;
	}

	public void setShipToPhone(String shipToPhone) {
		this.shipToPhone = shipToPhone;
	}

	public String getShipToAffiliation() {
		return shipToAffiliation;
	}

	public void setShipToAffiliation(String shipToAffiliation) {
		this.shipToAffiliation = shipToAffiliation;
	}

	public String getShipToAffiliationPhone() {
		return shipToAffiliationPhone;
	}

	public void setShipToAffiliationPhone(String shipToAffiliationPhone) {
		this.shipToAffiliationPhone = shipToAffiliationPhone;
	}

	public String getShipToAffiliationEmail() {
		return shipToAffiliationEmail;
	}

	public void setShipToAffiliationEmail(String shipToAffiliationEmail) {
		this.shipToAffiliationEmail = shipToAffiliationEmail;
	}

	public String getShipToAffiliationSpecialInstructions() {
		return shipToAffiliationSpecialInstructions;
	}

	public void setShipToAffiliationSpecialInstructions(
			String shipToAffiliationSpecialInstructions) {
		this.shipToAffiliationSpecialInstructions = shipToAffiliationSpecialInstructions;
	}

}
