//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.31 at 05:32:23 AM EDT 
//


package gov.nih.tbi.ordermanager.iu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CoriellId"/>
 *         &lt;element ref="{}GUID"/>
 *         &lt;element ref="{}SpecimenType"/>
 *         &lt;element ref="{}OriginalContainerTypeReceived"/>
 *         &lt;element ref="{}Subcollection"/>
 *         &lt;element ref="{}VisitDescription"/>
 *         &lt;element ref="{}NumberOfAliquots"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coriellId",
    "guid",
    "specimenType",
    "originalContainerTypeReceived",
    "subcollection",
    "visitDescription",
    "numberOfAliquots",
    "repository"
})
@XmlRootElement(name = "SampleRequest")
public class SampleRequest {

    @XmlElement(name = "CoriellId", required = true)
    protected String coriellId;
    @XmlElement(name = "GUID", required = true)
    protected String guid;
    @XmlElement(name = "SpecimenType", required = true)
    protected String specimenType;
    @XmlElement(name = "OriginalContainerTypeReceived", required = true)
    protected String originalContainerTypeReceived;
    @XmlElement(name = "Subcollection", required = true)
    protected String subcollection;
    @XmlElement(name = "VisitDescription", required = true)
    protected String visitDescription;
    @XmlElement(name = "NumberOfAliquots", required = true)
    protected String numberOfAliquots;
    public String getRepository() {
		return repository;
	}

	public void setRepository(String repository) {
		this.repository = repository;
	}

	@XmlElement(name = "Repository", required = true)
    protected String repository;

    /**
     * Gets the value of the coriellId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoriellId() {
        return coriellId;
    }

    /**
     * Sets the value of the coriellId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoriellId(String value) {
        this.coriellId = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGUID() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGUID(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the specimenType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenType() {
        return specimenType;
    }

    /**
     * Sets the value of the specimenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenType(String value) {
        this.specimenType = value;
    }

    /**
     * Gets the value of the originalContainerTypeReceived property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalContainerTypeReceived() {
        return originalContainerTypeReceived;
    }

    /**
     * Sets the value of the originalContainerTypeReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalContainerTypeReceived(String value) {
        this.originalContainerTypeReceived = value;
    }

    /**
     * Gets the value of the subcollection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcollection() {
        return subcollection;
    }

    /**
     * Sets the value of the subcollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcollection(String value) {
        this.subcollection = value;
    }

    /**
     * Gets the value of the visitDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitDescription() {
        return visitDescription;
    }

    /**
     * Sets the value of the visitDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitDescription(String value) {
        this.visitDescription = value;
    }

    /**
     * Gets the value of the numberOfAliquots property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfAliquots() {
        return numberOfAliquots;
    }

    /**
     * Sets the value of the numberOfAliquots property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfAliquots(String value) {
        this.numberOfAliquots = value;
    }

}
