openapi: 3.0.0
info:
  description: Allows users to interact with their Download Queue to add datasets, remove them, and get a list of what's in their queue
  version: 1.0.0
  title: Download Tool

  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
    
servers:
  - url: http://localhost:8083/
tags:
  - name: downloadQueue
    description: Download Queue interaction endpoints
paths:
  /queue/{datasetId}:
    put:
      tags:
      - downloadQueue
      summary: (EXPERIMENTAL ONLY) Add a new dataset to the download queue
      operationId: addToQueue
      parameters:
      - name: datasetId
        in: path
        description: ID of dataset to add to the download queue
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Successfully added dataset to the download queue
        400:
          description: Invalid ID supplied
         
  /queue:
    delete:
      tags:
      - downloadQueue
      summary: Remove one or more downloadables from the download queue
      description: ""
      operationId: removeFromQueue
      parameters:
      - name: downloadableIds
        in: query
        description: IDs of downloadables to remove from the download queue
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        200:
          description: Successfully removed
        400:
          description: no IDs were sent
        401:
          description: supplied user may not delete these downloadables
          
    get:
      tags:
      - downloadQueue
      summary: Get all download packages in the user's download queue
      operationId: getAll
      responses:
        200:
          description: list obtained successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DownloadToolPackage"
                  
  /queue/package/{packageId}:
    delete:
      tags:
      - downloadQueue
      summary: Remove an entire download package from the queue
      description: ""
      operationId: removePackageFromQueue
      parameters:
      - name: packageId
        in: path
        description: IDs of package to remove from the download queue
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Successfully removed
        400:
          description: no ID was sent
        401:
          description: supplied user may not delete this package  

components:
  securitySchemes:
    bearerAuth:
       type: http
       scheme: bearer
       bearerFormat: JWT
  schemas:
    DownloadToolPackage:
      type: object
      required:
      - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        dateAdded:
          type: integer
          format: int64
        origin:
          type: string
          enum: [QUERY_TOOL, DATASET, ACCOUNT]
        downloadables:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
              type:
                type: string
              userFile:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  description:
                    type: string
                  path:
                    type: string
                  study:
                    type: string
                  size:
                    type: integer
                    format: int64
                  # will need others here from UserFile
  
security:
  - bearerAuth: []