openapi: 3.0.0
info:
  description: Allows users to validate submission packages before actual submission then accept the submission packages for insertion into the repository
  version: 1.0.0
  title: Submission Tool

  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
    
servers:
  - url: http://localhost:6084/
tags:
  - name: validation
    description: Validation Tool interaction webservice endpoints
  - name: submission
    description: Submission Tool interaction webservice endpoints
paths:
  /validate:
    post:
      tags:
      - validation
      summary: "Validate the data in the main CSV and associated files"
      operationId: validate
      requestBody:
        content:
          multipart/form-data:
            schema: 
              $ref: '#/components/schemas/ValidationPackage'
      responses:
        200:
          description: "the package validated correctly"
          content: 
            text/plain:
              schema:
                type: string
                description: string content of the submission package xml file
        400:
          description: errors were found that prevent successful submission
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/ValidationErrorsWarning'
                  

components:
  securitySchemes:
    bearerAuth:
       type: http
       scheme: bearer
       bearerFormat: JWT
  schemas:
    ValidationPackage:
      type: object
      required:
      - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        dateAdded:
          type: integer
          format: int64
        origin:
          type: string
          enum: [QUERY_TOOL, DATASET, ACCOUNT]
        associatedFiles:
          type: array
          items:
            type: string
            
    ValidationErrorsWarning:
      type: object
      properties:
        type: 
          type: string
          enum: ["error", "warning"]
        message:
          type: string
          description: "The message of the actual string"
  
security:
  - bearerAuth: []