//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.31 at 05:32:23 AM EDT 
//


package gov.nih.tbi.ordermanager.coriell;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IsFunded"/>
 *         &lt;element ref="{}UnderReview"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isFunded",
    "underReview"
})
@XmlRootElement(name = "FundingStatus")
public class FundingStatus {

    @XmlElement(name = "IsFunded", required = true)
    protected IsFunded isFunded;
    @XmlElement(name = "UnderReview", required = true)
    protected UnderReview underReview;

    /**
     * Gets the value of the isFunded property.
     * 
     * @return
     *     possible object is
     *     {@link IsFunded }
     *     
     */
    public IsFunded getIsFunded() {
        return isFunded;
    }

    /**
     * Sets the value of the isFunded property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsFunded }
     *     
     */
    public void setIsFunded(IsFunded value) {
        this.isFunded = value;
    }

    /**
     * Gets the value of the underReview property.
     * 
     * @return
     *     possible object is
     *     {@link UnderReview }
     *     
     */
    public UnderReview getUnderReview() {
        return underReview;
    }

    /**
     * Sets the value of the underReview property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderReview }
     *     
     */
    public void setUnderReview(UnderReview value) {
        this.underReview = value;
    }

}
