//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.31 at 05:32:23 AM EDT 
//


package gov.nih.tbi.ordermanager.coriell;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FundingTimeline"/>
 *         &lt;element ref="{}FundingAgency"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundingTimeline",
    "fundingAgency"
})
@XmlRootElement(name = "UnderReview")
public class UnderReview {

    @XmlElement(name = "FundingTimeline", required = true)
    protected String fundingTimeline;
    @XmlElement(name = "FundingAgency", required = true)
    protected String fundingAgency;

    /**
     * Gets the value of the fundingTimeline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundingTimeline() {
        return fundingTimeline;
    }

    /**
     * Sets the value of the fundingTimeline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundingTimeline(String value) {
        this.fundingTimeline = value;
    }

    /**
     * Gets the value of the fundingAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundingAgency() {
        return fundingAgency;
    }

    /**
     * Sets the value of the fundingAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundingAgency(String value) {
        this.fundingAgency = value;
    }

}
