//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 01:59:27 PM EDT 
//


package gov.nih.tbi.dictionary.service.rulesengine.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChangeSeverity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeSeverity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Increase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NoChange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Decrease" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeSeverity", propOrder = {
    "increase",
    "noChange",
    "decrease"
})
public class ChangeSeverity {

    @XmlElement(name = "Increase", required = true)
    protected String increase;
    @XmlElement(name = "NoChange", required = true)
    protected String noChange;
    @XmlElement(name = "Decrease", required = true)
    protected String decrease;

    /**
     * Gets the value of the increase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncrease() {
        return increase;
    }

    /**
     * Sets the value of the increase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncrease(String value) {
        this.increase = value;
    }

    /**
     * Gets the value of the noChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoChange() {
        return noChange;
    }

    /**
     * Sets the value of the noChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoChange(String value) {
        this.noChange = value;
    }

    /**
     * Gets the value of the decrease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecrease() {
        return decrease;
    }

    /**
     * Sets the value of the decrease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecrease(String value) {
        this.decrease = value;
    }

}
