//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 10:22:47 AM EDT 
//

package gov.nih.tbi.dictionary.service.rulesengine.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Field complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rule" type="{http://www.example.org/RulesEngineRules}Rule" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FieldList" type="{http://www.example.org/RulesEngineRules}FieldList" minOccurs="0"/>
 *         &lt;element name="SubField" type="{http://www.example.org/RulesEngineRules}Field" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Field", propOrder = { "name", "displayName", "rule", "fieldList", "subField" })
public class Field
{

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "DisplayName")
    protected String displayName;
    @XmlElement(name = "Rule")
    protected List<Rule> rule;
    @XmlElement(name = "FieldList")
    protected FieldList fieldList;
    @XmlElement(name = "SubField")
    protected List<Field> subField;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName()
    {

        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(String value)
    {

        this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisplayName()
    {

        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisplayName(String value)
    {

        this.displayName = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Rule }
     * 
     * 
     */
    public List<Rule> getRule()
    {

        if (rule == null)
        {
            rule = new ArrayList<Rule>();
        }
        return this.rule;
    }

    /**
     * Gets the value of the fieldList property.
     * 
     * @return possible object is {@link FieldList }
     * 
     */
    public FieldList getFieldList()
    {

        return fieldList;
    }

    /**
     * Sets the value of the fieldList property.
     * 
     * @param value
     *            allowed object is {@link FieldList }
     * 
     */
    public void setFieldList(FieldList value)
    {

        this.fieldList = value;
    }

    /**
     * Gets the value of the subField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the subField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSubField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Field }
     * 
     * 
     */
    public List<Field> getSubField()
    {

        if (subField == null)
        {
            subField = new ArrayList<Field>();
        }
        return this.subField;
    }

}
