//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 01:59:27 PM EDT 
//

package gov.nih.tbi.dictionary.service.rulesengine.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * gov.nih.tbi.dictionary.service.rulesengine.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _RulesEngineRule_QNAME = new QName("http://www.example.org/RulesEngineRules",
            "RulesEngineRule");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * gov.nih.tbi.dictionary.service.rulesengine.model
     * 
     */
    public ObjectFactory()
    {

    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule()
    {

        return new Rule();
    }

    /**
     * Create an instance of {@link DictionaryObjectRules }
     * 
     */
    public DictionaryObjectRules createDictionaryObjectRules()
    {

        return new DictionaryObjectRules();
    }

    /**
     * Create an instance of {@link ThresholdPropertyRules }
     * 
     */
    public ThresholdPropertyRules createThresholdPropertyRules()
    {

        return new ThresholdPropertyRules();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public FieldList createList()
    {

        return new FieldList();
    }

    /**
     * Create an instance of {@link ChangeSeverity }
     * 
     */
    public ChangeSeverity createChangeSeverity()
    {

        return new ChangeSeverity();
    }

    /**
     * Create an instance of {@link ThresholdChange }
     * 
     */
    public ThresholdChange createThresholdChange()
    {

        return new ThresholdChange();
    }

    /**
     * Create an instance of {@link Threshold }
     * 
     */
    public Threshold createThreshold()
    {

        return new Threshold();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField()
    {

        return new Field();
    }

    /**
     * Create an instance of {@link RulesEngineRule }
     * 
     */
    public RulesEngineRules createRulesEngineRule()
    {

        return new RulesEngineRules();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RulesEngineRule }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/RulesEngineRules", name = "RulesEngineRule")
    public JAXBElement<RulesEngineRules> createRulesEngineRule(RulesEngineRules value)
    {

        return new JAXBElement<RulesEngineRules>(_RulesEngineRule_QNAME, RulesEngineRules.class, null, value);
    }

}
