//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.15 at 12:13:03 PM EDT 
//

package gov.nih.tbi.dictionary.service.rulesengine.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Operation.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="Operation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Added"/>
 *     &lt;enumeration value="Remove"/>
 *     &lt;enumeration value="Sequence"/>
 *     &lt;enumeration value="NotEqual"/>
 *     &lt;enumeration value="LessThan"/>
 *     &lt;enumeration value="MoreThan"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Operation")
@XmlEnum
public enum Operation
{

    @XmlEnumValue("Added")
    ADDED("Added"), @XmlEnumValue("Removed")
    REMOVE("Removed"), @XmlEnumValue("Sequence")
    SEQUENCE("Sequence"), @XmlEnumValue("NotEqual")
    NOT_EQUAL("NotEqual"), @XmlEnumValue("LessThan")
    LESS_THAN("LessThan"), @XmlEnumValue("GreaterThan")
    GREATER_THAN("GreaterThan");

    private final String value;

    Operation(String v)
    {

        value = v;
    }

    public String value()
    {

        return value;
    }

    public static Operation fromValue(String v)
    {

        for (Operation c : Operation.values())
        {
            if (c.value.equals(v))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
