//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.17 at 03:00:46 PM EDT 
//

package gov.nih.tbi.dictionary.service.rulesengine.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Rule complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.example.org/RulesEngineRules}Operation"/>
 *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ThresholdPropertiesRules" type="{http://www.example.org/RulesEngineRules}ThresholdPropertyRules" minOccurs="0"/>
 *         &lt;element name="DataElementOptionality" type="{http://www.example.org/RulesEngineRules}DataElementOptionality" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rule", propOrder = { "operation", "severity", "thresholdPropertiesRules", "dataElementOptionality" })
public class Rule
{

    @XmlElement(name = "Operation", required = true)
    protected Operation operation;
    @XmlElement(name = "Severity", required = true)
    protected String severity;
    @XmlElement(name = "ThresholdPropertiesRules")
    protected ThresholdPropertyRules thresholdPropertiesRules;
    @XmlElement(name = "DataElementOptionality")
    protected DataElementOptionality dataElementOptionality;

    /**
     * Gets the value of the operation property.
     * 
     * @return possible object is {@link Operation }
     * 
     */
    public Operation getOperation()
    {

        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *            allowed object is {@link Operation }
     * 
     */
    public void setOperation(Operation value)
    {

        this.operation = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeverity()
    {

        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeverity(String value)
    {

        this.severity = value;
    }

    /**
     * Gets the value of the thresholdPropertiesRules property.
     * 
     * @return possible object is {@link ThresholdPropertyRules }
     * 
     */
    public ThresholdPropertyRules getThresholdPropertiesRules()
    {

        return thresholdPropertiesRules;
    }

    /**
     * Sets the value of the thresholdPropertiesRules property.
     * 
     * @param value
     *            allowed object is {@link ThresholdPropertyRules }
     * 
     */
    public void setThresholdPropertiesRules(ThresholdPropertyRules value)
    {

        this.thresholdPropertiesRules = value;
    }

    /**
     * Gets the value of the dataElementOptionality property.
     * 
     * @return possible object is {@link DataElementOptionality }
     * 
     */
    public DataElementOptionality getDataElementOptionality()
    {

        return dataElementOptionality;
    }

    /**
     * Sets the value of the dataElementOptionality property.
     * 
     * @param value
     *            allowed object is {@link DataElementOptionality }
     * 
     */
    public void setDataElementOptionality(DataElementOptionality value)
    {

        this.dataElementOptionality = value;
    }

}
