//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.15 at 12:13:03 PM EDT 
//

package gov.nih.tbi.dictionary.service.rulesengine.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RulesEngineRule complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RulesEngineRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataElementRules" type="{http://www.example.org/RulesEngineRules}DictionaryObjectRules"/>
 *         &lt;element name="FormStructureRules" type="{http://www.example.org/RulesEngineRules}DictionaryObjectRules"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RulesEngineRules", propOrder = { "dataElementRules", "formStructureRules" })
public class RulesEngineRules
{

    @XmlElement(name = "DataElementRules", required = true)
    protected DictionaryObjectRules dataElementRules;
    @XmlElement(name = "FormStructureRules", required = true)
    protected DictionaryObjectRules formStructureRules;

    /**
     * Gets the value of the dataElementRules property.
     * 
     * @return possible object is {@link DictionaryObjectRules }
     * 
     */
    public DictionaryObjectRules getDataElementRules()
    {

        return dataElementRules;
    }

    /**
     * Sets the value of the dataElementRules property.
     * 
     * @param value
     *            allowed object is {@link DictionaryObjectRules }
     * 
     */
    public void setDataElementRules(DictionaryObjectRules value)
    {

        this.dataElementRules = value;
    }

    /**
     * Gets the value of the formStructureRules property.
     * 
     * @return possible object is {@link DictionaryObjectRules }
     * 
     */
    public DictionaryObjectRules getFormStructureRules()
    {

        return formStructureRules;
    }

    /**
     * Sets the value of the formStructureRules property.
     * 
     * @param value
     *            allowed object is {@link DictionaryObjectRules }
     * 
     */
    public void setFormStructureRules(DictionaryObjectRules value)
    {

        this.formStructureRules = value;
    }

}
