//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 01:59:27 PM EDT 
//


package gov.nih.tbi.dictionary.service.rulesengine.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThresholdChange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThresholdChange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChangeSeverity" type="{http://www.example.org/RulesEngineRules}ChangeSeverity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThresholdChange", propOrder = {
    "name",
    "changeSeverity"
})
public class ThresholdChange {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "ChangeSeverity", required = true)
    protected ChangeSeverity changeSeverity;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the changeSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeSeverity }
     *     
     */
    public ChangeSeverity getChangeSeverity() {
        return changeSeverity;
    }

    /**
     * Sets the value of the changeSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeSeverity }
     *     
     */
    public void setChangeSeverity(ChangeSeverity value) {
        this.changeSeverity = value;
    }

}
