openapi: 3.0.0
info:
  description: This is an API to access Repository data (metadata/metastudy/datasets in both).
  version: 1.0.0
  title: Repository API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://localhost:6084
  
tags:
  - name: study
    description: Study related endpoints
  - name: metastudy
    description: Metastudy related endpoints
  - name: dataset
    description: Datasets related endpoints
    
paths:
  /study:
    get:
      tags:
      - study
      summary: Get studies
      description: Get the list of studies the authorized user has access to."
      operationId: getStudies
      responses:
        200:
            description: "successful operation"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Study"
        401:
          $ref: "#/components/responses/UnauthorizedError"
      security:
      - Bearer: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: JWT is missing or invalid
    NotFoundError:
      description: The specified resource was not found
  schemas:
    Study:
      type: "object"
      properties:
        status:
          type: "string"
          enum: ["Private", "Public"]
        id:
          type: "string"
        title:
          type: "string"
        pi:
          type: "string"
        abstract:
          type: "string"
security:
  - bearerAuth: []